
dist: xenial

sudo: required

language: go

before_install:
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
        sudo sed -i 's|xenial|bionic|g' /etc/apt/sources.list &&
        sudo apt-get update &&
        sudo apt-get dist-upgrade &&
        sudo apt-get install i2pd &&
        sudo cp etc/i2pd/i2pd.si-i2p-plugin.conf /etc/i2pd/i2pd.conf
    ; else
        wget -O i2pd.tar.gz https://github.com/PurpleI2P/i2pd/releases/download/2.19.0/i2pd_2.19.0_osx.tar.gz;
    fi

install: sudo service i2pd start && make deps gotest noopts
