
dist: xenial

sudo: required

language: go

before_install:
    sudo sed -i 's|xenial|bionic|g' /etc/apt/sources.list &&
    sudo apt-get update &&
    sudo apt-get install i2pd &&
    sudo cp etc/i2pd/i2pd.si-i2p-plugin.conf /etc/i2pd/i2pd.conf

install: sudo service i2pd start && make gotest release
